name: HammerCore
version: '${version}'
main: ink.ziip.hammer.hammercore.HammerCore
api-version: '1.20'
authors: [ EterLzb ]
description: Core plugin of TrialHammer.
depend:
  - ProtocolLib
  - PlaceholderAPI
  - floodgate
softdepend:
  - ProjectKorra
  - Brewery
  - Spartan
commands:
  hammercore:
    description: Core command.
    usage: /<command>
  menu:
    description: Opening menu command.
    usage: /<command>